#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 8 -padding 20 -lines 5 -font "Hack 15" <<< "Lock|Sleep|Logout|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Sleep) i3lock-fancy && systemctl hibernate ;;
                *Logout) i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
